---
title: "hw6"
output: html_document
date: "2024-12-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(modelr)
library(broom)
library(crossval)
```

---

### Problem 2

```{r}
#load the data
homicides <- read_csv("./data/homicide-data.csv")
```

```{r}
homicides <- homicides %>%
  mutate(
    city_state = str_c(city, ", ", state),
    solved_binary = if_else(disposition == "Closed by arrest", 1, 0),
    victim_age = as.numeric(victim_age)
  ) %>%
  filter(
    !city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"),
    victim_race %in% c("White", "Black"),
    !is.na(victim_age)
  )
head(homicides)
```

```{r}
#only baltimore data
baltimore <- homicides %>% 
  filter(city_state == "Baltimore, MD")

#ffit logistic regression model
baltimore_glm <- glm(
  solved_binary ~ victim_age + victim_sex + victim_race,
  family = binomial(),
  data = baltimore
)

#obtain odds ratio for male victims
baltimore_or <- broom::tidy(baltimore_glm) %>%
  filter(term == "victim_sexMale") %>%
  mutate(
    or = exp(estimate),
    ci_lower = exp(estimate - 1.96 * std.error),
    ci_upper = exp(estimate + 1.96 * std.error)
  )
baltimore_or 
```

```{r}
#logistic regression for all cities
cities <- homicides %>%
  group_by(city_state) %>%
  nest() %>%
  mutate(
    model = map(data, ~ glm(
      solved_binary ~ victim_age + victim_sex + victim_race,
      family = binomial(),
      data = .
    )),
    tidy_model = purrr::map(model, broom::tidy)
  ) %>%
  unnest(tidy_model) %>%
  filter(term == "victim_sexMale") %>%
  mutate(
    or = exp(estimate),
    ci_lower = exp(estimate - 1.96 * std.error),
    ci_upper = exp(estimate + 1.96 * std.error)
  ) %>%
  select(city_state, or, ci_lower, ci_upper)

cities %>%
  slice(1:5) %>%
  knitr::kable(digits = 3)
```

```{r}
#plot
cities %>%
  ggplot(aes(x = fct_reorder(city_state, or), y = or)) +
  geom_point() +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0.2) +
  coord_flip() +
  labs(
    title = "Adjusted Odds Ratios for Solving Homicides",
    x = "City, State",
    y = "Adjusted Odds Ratio"
  ) +
  theme_minimal()

```
Most cities smaller than OR of 1, indicating that after controlling for victim age and race, the likelihood of a crime involving a male victim being resolved is lower than that of a crime involving a female victim.

---

### Problem 3

```{r}
birthweight <- read_csv("./data/birthweight.csv")
```
```{r}
birthweight <- birthweight %>%
  janitor::clean_names() %>%
  mutate(
    babysex = factor(babysex, levels = c(1,2), labels = c("male", "female")),
    malform = case_when(malform == 0 ~ "absent", malform == 1 ~ "present"),
    mrace = factor(mrace, levels = c(1,2,3,4,8), labels = c("White", "Black", "Asian", "Puerto Rican", "Other")),
    frace = factor(frace, levels = c(1,2,3,4,8,9), labels = c("White", "Black", "Asian", "Puerto Rican", "Other", "Unknow"))) %>%
  drop_na() 
```

```{r}
#fit the proposed regression model
mymodel <- lm(bwt ~ gaweeks + wtgain + babysex + malform, data = birthweight)


#add some predictions and residuals
birthweight <- birthweight %>%
  modelr::add_predictions(mymodel, var = "fitted") %>%
  modelr::add_residuals(mymodel, var = "residuals")

```

```{r}
#plot
birthweight %>%
  ggplot(aes(x = fitted, y = residuals)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "loess", color = "blue", se = FALSE) +
  labs(
    title = "Residuals vs Fitted Values",
    x = "Fitted Values",
    y = "Residuals"
  ) +
  theme_minimal()
```

